name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Mattraks'

inputs:
  token:
    description: 'Authentication token'
    required: true
    default: ${{ github.token }}

  baseUrl:
    description: 'Base API URL'
    required: false
    default: "https://api.github.com"

  repository:
    description: 'Name of the repository'
    required: true
    default: ${{ github.repository }}

  retain_days:
    description: 'Days-worth of runs to keep for each workflow'
    required: true
    default: 30

  keep_minimum_runs:
    description: 'Minimum runs to keep for each workflow'
    required: true
    default: 6

  delete_workflow_pattern:
    description: 'Name or filename of the workflow (if not set, all workflows are targeted)'
    required: false

  delete_workflow_by_state_pattern:
    description: 'Filter workflows by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
    required: false

  delete_run_by_conclusion_pattern:
    description: 'Remove runs based on conclusion: action_required, cancelled, failure, skipped, success'
    required: false

  dry_run:
    description: 'Logs simulated changes, no deletions are performed'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
